### PR TITLE
Pretty bad but useable explaination for how to use it in windows.

### PR DESCRIPTION
**Pull request by sryu1**

### CODE REVIEW

**Comment by magnetic-eagle** [comment]
What do you mean with `Copy the code you want to use into the repository (but not into the subfolders)` ? What code ?

**Comment by sryu1** [comment]
oh, the code file, I meant.

**Comment by magnetic-eagle** [comment]
do you mean the scripts from the aircraft and scenery subfolders or what ?

**Review by magnetic-eagle — APPROVED** [review]

**Comment by sryu1** [comment]
It's not merged yet hahaha

**Comment by magnetic-eagle** [comment]
Yes, because I do not understand what you want to say with that phrase. Why should anyone copy any files into the local repository ?

**Comment by sryu1** [comment]
Is it possible if we could make fgtools a pypi package?

**Comment by magnetic-eagle** [comment]
I guess so  ! :)

**Comment by magnetic-eagle** [comment]
#4

**Pull request closed without merging**
